### PR TITLE
first pass updating readme and guide docs

### PR DESCRIPTION
**Pull request by choldgraf**
Following #32 this is a first-pass attempt at reorganizing and adding some new information to the README and guide for instructors. Maybe folks there would be interested in giving comments and thoughts. Anything you think would improve this is useful.

All of the additions are in the `guide` section, which is a root-level folder of the repository. I tried to add a few sections that I think would be useful, but that don't have information yet. If you have an idea for how to populate those empty sections with info, then post it here!

Maybe @pattyf @cboettig and @dfeehan have thoughts on stuff specific to course organization / structure / etc, and @ryanlovett and @SamLau95 have thoughts on some of the technical stuff? But chime in wherever it's useful!

### CODE REVIEW

**Comment by SamLau95** [comment]
This looks good to me! Do you have merge permissions? I think in the future you can just merge it yourself.

**Comment by choldgraf** [comment]
Yeah I know I can just merge it, but was hoping to have some discussions and thoughts before doing so :P

**Comment by choldgraf** [comment]
but, we should get this merged sooner than later so that it's there for new instructors

**Comment by SamLau95** [comment]
Yeah, that's what I was thinking too. I think we can just merge it in now and then have more discussion as the semester begins and we resume the connector instructor meetings?

**Comment by choldgraf** [comment]
done :D

**Pull request merged**
